---
# tasks file for bacula_client
#
- name: install bacula client
  apt:
    name:
    - bacula-client

- name: template bacula-fd
  template:
    src: "bacula-fd.j2"
    dest: "/etc/bacula/bacula-fd.conf"

