---
# tasks file for kibana
- name: install kibana
  apt:
    name: 
    - kibana

- name: rest
  shell:
    cmd: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -b
  register: reset_cmd

- name: template kibana
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml

- name: create dir
  file:
    path: "{{ kib_certs }}"
    state: directory

- name: copy sign serts elastic
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - { src: "{{ http_ca }}", dest: "{{ kib_certs }}" }
    - { src: "{{ http }}", dest: "{{ kib_certs }}" }
    - { src: "{{ transport }}", dest: "{{ kib_certs }}" }

- name: change mode
  file:
    path: "{{ kib_certs }}"
    state: directory
    recurse: yes
    owner: root
    group: kibana

- name: service enable
  service:
    name: kibana 
    state: started
    enabled: yes

