---
# handlers file for bacula

- name: restart-dir
  service:
    name: bacula-dir
    state: restarted
    enabled: true

- name: restart-sd
  service:
    name: bacula-sd
    state: restarted
    enabled: true

