---
# tasks file for ntpd
 
 - name: install all
   apt:
     name: 
     - ntp
     state: latest

 - name: ntp
   template: 
     src: ntp.j2
     dest: /etc/ntpsec/ntp.conf

 - name: restart
   timezone:
    hwclock: local
    name: Europe/Moscow


 - name: restart
   service:
     name: ntpd 
     state: restarted
     enabled: true
