---
# tasks file for ntpd
 
 - name: install all
   apt:
     name: 
     - ntp
     state: latest

 - name: ntp
   template: 
     src: ntp.j2
     dest: /etc/ntp.conf
 
 - name: restart
   service:
     name: ntpd 
     state: restarted
     enabled: true


