---
# tasks file for bacula

- name: install server  
  apt:
    update_cache: yes
    name:
    - bacula
    - bacula-director-pgsql
    - ca-certificates
    - libpq-dev 
    - python3-dev
    - python3-psycopg2

- name: templ
  template:
    src: "pg_hba.j2"   
    dest: "/etc/postgresql/15/main/pg_hba.conf"

- name: change postgres pref
  lineinfile:
    path: "/etc/postgresql/15/main/postgresql.conf"
    regexp: "^listen_addresses"
    line: "listen_addresses = '192.168.2.10'"

- name: service start and enabled
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: add user bacula
  postgresql_user:
    login_user: postgres
    name: bacula
    password: "1qaz@WSX"

- name: create basese bacula
  postgresql_db:
    name: "bacula"
    owner: "bacula" 
    template: template0
  
- name: grant db bacula
  postgresql_privs:
    db: "bacula"
    type: database
    privs: "ALL"
    role: "bacula"

- name: templ hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: create folder for backup
  file:
    path: /var/bacula/node
    state: directory
    owner: bacula
    group: bacula

- name: create folder for backup
  file:
    path: /tmp/restore
    state: directory
    owner: bacula
    group: bacula

- name: template bacula-dir
  template:
    src: bacula-dir.j2
    dest: /etc/bacula/bacula-dir.conf
    owner: bacula
    group: www-data
    mode: '775'
  notify:
  - restart-dir

- name: template bacula-sd
  template:
    src: bacula-sd.j2
    dest: /etc/bacula/bacula-sd.conf
  notify:
  - restart-sd

- name: Add bacula console config
  template:
    src: "bconsole.j2"
    dest: "/etc/bacula/bconsole.conf"


...
