---
# tasks file for haprox
    - name: install iptables-persisten
      apt:
        update_cache: yes
        name:
        - iptables-persistent
        - nginx
        state: latest
    
    - name: start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: rules nat
      template:
        src: iptables
        dest: /etc/iptables/rules.v4
        

    - name: enable forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
    
    - name: add templ
      template:
        src: nginx_proxy
        dest: /etc/nginx/sites-available/default 
