---
# tasks file for elasticsearch
- name:
  apt:
    name: 
    - elasticsearch

- name: preference elast
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#network.host: 192.168.0.1", line: "network.host: 127.0.0.1"}
    - { regexp: "http.host: 0.0.0.0" , line: "http.host: 127.0.0.1"}

- name: service enable
  service:
    name: elasticsearch 
    state: started
    enabled: yes
    



  
