---
- name: Reboot
  reboot:
    msg: "ansible_os_family"
    pre_reboot_delay: 0
    post_reboot_delay: 30






#v2
# tasks file for rebooted
#- name: reboot all hosts
#  block:
#  - shell: systemctl reboot
#    async: 300
#    poll: 0
#    ignore_errors: true

#  - name: wait for system hosts
#    wait_for_connection:
#    delay: 60
#    timeout: 300

