---
# tasks file for galera_db
- name: service sql stop
  service:
    name: mysql
    state: stopped
  ignore_errors: true

- name: create dir 
  file:
    path: /var/log/mysql
    state: directory
    recurse: yes
    owner: mysql
    group: mysql
    mode: '0755'
      
      #- name: add conf server mysql
      #template:
      #src: mysql.j2
      #dest: /etc/mysql/mariadb.conf.d/50-server.cnf
- name: change mysql pref
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address"
    line: "#bind-address"


- name: add conf galera
  template:
    src: galera.j2
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf

    
- name: intivialisation
  command: 'galera_new_cluster'
  when: (ansible_hostname == "node1")
  ignore_errors: true

- name:
  service:
    name: mysql
    state: started
    enabled: yes    

